sonar.projectKey=dinhhhiuu_react-native-expo
sonar.organization=dinhhhiuu
sonar.host.url=https://sonarcloud.io

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=react-native-expo
sonar.projectVersion=1.0

# Sources and tests
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclude folders and files not relevant to analysis
sonar.exclusions=node_modules/**,coverage/**,**/*.config.js,**/android/**,**/ios/**,.expo/**,assets/**,.github/**
sonar.coverage.exclusions=**/__tests__/**,**/*.test.*

# Coverage report (Jest produces coverage/lcov.info)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8